{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://lists.apache.org/thread/3dgvzgstycf8b5hyf4z3n7cqdhcyln3l",
            "tags": [
              "vendor-advisory",
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-02T11:03:19.260Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 9.8,
              "attackVector": "NETWORK",
              "baseSeverity": "CRITICAL",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "integrityImpact": "HIGH",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "HIGH"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2023-24831",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "total"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-10-21T14:14:59.918874Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:apache:iotdb:*:*:*:*:*:*:*:*"
            ],
            "vendor": "apache",
            "product": "iotdb",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "versionType": "custom",
                "lessThanOrEqual": "0.13.3"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-10-21T14:17:28.977Z"
        }
      }
    ],
    "cna": {
      "title": "Apache IoTDB grafana-connector Login Bypass Vulnerability",
      "source": {
        "discovery": "UNKNOWN"
      },
      "metrics": [
        {
          "other": {
            "type": "Textual description of severity",
            "content": {
              "text": "low"
            }
          }
        }
      ],
      "affected": [
        {
          "vendor": "Apache Software Foundation",
          "product": "Apache IoTDB",
          "versions": [
            {
              "status": "affected",
              "version": "0.13.0",
              "versionType": "semver",
              "lessThanOrEqual": "0.13.3"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "references": [
        {
          "url": "https://lists.apache.org/thread/3dgvzgstycf8b5hyf4z3n7cqdhcyln3l",
          "tags": [
            "vendor-advisory"
          ]
        }
      ],
      "x_generator": {
        "engine": "Vulnogram 0.1.0-dev"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "Improper Authentication vulnerability in Apache Software Foundation Apache IoTDB.This issue affects Apache IoTDB Grafana Connector: from 0.13.0 through 0.13.3.\n\nAttackers could login without authorization. This is fixed in 0.13.4.",
          "supportingMedia": [
            {
              "type": "text/html",
              "value": "Improper Authentication vulnerability in Apache Software Foundation Apache IoTDB.<p>This issue affects Apache IoTDB Grafana Connector: from 0.13.0 through 0.13.3.</p>Attackers could login without authorization. This is fixed in 0.13.4.",
              "base64": false
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-287",
              "description": "CWE-287 Improper Authentication"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
        "shortName": "apache",
        "dateUpdated": "2023-04-17T06:42:06.404Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2023-24831",
    "state": "PUBLISHED",
    "dateUpdated": "2024-10-21T14:17:36.529Z",
    "dateReserved": "2023-01-30T15:53:19.799Z",
    "assignerOrgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
    "datePublished": "2023-04-17T06:42:06.404Z",
    "assignerShortName": "apache"
  },
  "dataVersion": "5.1"
}