{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/py-pdf/pypdf/security/advisories/GHSA-4vvm-4w3v-6mr8",
            "name": "https://github.com/py-pdf/pypdf/security/advisories/GHSA-4vvm-4w3v-6mr8",
            "tags": [
              "x_refsource_CONFIRM",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/py-pdf/pypdf/pull/1828",
            "name": "https://github.com/py-pdf/pypdf/pull/1828",
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/py-pdf/pypdf/pull/969",
            "name": "https://github.com/py-pdf/pypdf/pull/969",
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-02T16:45:57.117Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2023-36464",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-12-03T16:55:56.361143Z"
              }
            }
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-12-03T16:56:00.627Z"
        }
      }
    ],
    "cna": {
      "title": "Infinite Loop when a comment isn't followed by a character in pypdf",
      "source": {
        "advisory": "GHSA-4vvm-4w3v-6mr8",
        "discovery": "UNKNOWN"
      },
      "metrics": [
        {
          "cvssV3_1": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 6.2,
            "attackVector": "LOCAL",
            "baseSeverity": "MEDIUM",
            "vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "HIGH",
            "privilegesRequired": "NONE",
            "confidentialityImpact": "NONE"
          }
        }
      ],
      "affected": [
        {
          "vendor": "py-pdf",
          "product": "pypdf",
          "versions": [
            {
              "status": "affected",
              "version": " pypdf: < 3.90"
            },
            {
              "status": "affected",
              "version": "PyPDF2: >= 2.2.0"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/py-pdf/pypdf/security/advisories/GHSA-4vvm-4w3v-6mr8",
          "name": "https://github.com/py-pdf/pypdf/security/advisories/GHSA-4vvm-4w3v-6mr8",
          "tags": [
            "x_refsource_CONFIRM"
          ]
        },
        {
          "url": "https://github.com/py-pdf/pypdf/pull/1828",
          "name": "https://github.com/py-pdf/pypdf/pull/1828",
          "tags": [
            "x_refsource_MISC"
          ]
        },
        {
          "url": "https://github.com/py-pdf/pypdf/pull/969",
          "name": "https://github.com/py-pdf/pypdf/pull/969",
          "tags": [
            "x_refsource_MISC"
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "pypdf is an open source, pure-python PDF library. In affected versions an attacker may craft a PDF which leads to an infinite loop if `__parse_content_stream` is executed. That is, for example, the case if the user extracted text from such a PDF. This issue was introduced in pull request #969 and resolved in pull request #1828. Users are advised to upgrade. Users unable to upgrade may modify the line `while peek not in (b\"\\r\", b\"\\n\")` in `pypdf/generic/_data_structures.py` to `while peek not in (b\"\\r\", b\"\\n\", b\"\")`."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-835",
              "description": "CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop')"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "shortName": "GitHub_M",
        "dateUpdated": "2023-06-27T21:24:30.685Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2023-36464",
    "state": "PUBLISHED",
    "dateUpdated": "2024-12-03T16:56:06.186Z",
    "dateReserved": "2023-06-21T18:50:41.700Z",
    "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
    "datePublished": "2023-06-27T21:24:30.685Z",
    "assignerShortName": "GitHub_M"
  },
  "dataVersion": "5.1"
}