{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://access.redhat.com/security/cve/CVE-2023-3361",
            "tags": [
              "vdb-entry",
              "x_refsource_REDHAT",
              "x_transferred"
            ]
          },
          {
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2216588",
            "name": "RHBZ#2216588",
            "tags": [
              "issue-tracking",
              "x_refsource_REDHAT",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/opendatahub-io/odh-dashboard/issues/1415",
            "tags": [
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-02T06:55:02.705Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2023-3361",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-09-19T19:18:17.893416Z"
              }
            }
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-09-19T19:18:23.918Z"
        }
      }
    ],
    "cna": {
      "title": "S3 credentials included when exporting elyra notebook",
      "metrics": [
        {
          "other": {
            "type": "Red Hat severity rating",
            "content": {
              "value": "Important",
              "namespace": "https://access.redhat.com/security/updates/classification/"
            }
          }
        },
        {
          "format": "CVSS",
          "cvssV3_1": {
            "scope": "CHANGED",
            "version": "3.1",
            "baseScore": 7.7,
            "attackVector": "NETWORK",
            "baseSeverity": "HIGH",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:N/A:N",
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "NONE",
            "privilegesRequired": "LOW",
            "confidentialityImpact": "HIGH"
          }
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "odh-dashboard",
          "versions": [
            {
              "status": "unaffected",
              "version": "1.28.1"
            }
          ]
        },
        {
          "cpes": [
            "cpe:/a:redhat:openshift_data_science"
          ],
          "vendor": "Red Hat",
          "product": "Red Hat OpenShift Data Science (RHODS)",
          "packageName": "rhods/odh-dashboard-rhel8",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "defaultStatus": "affected"
        }
      ],
      "timeline": [
        {
          "lang": "en",
          "time": "2023-06-21T00:00:00+00:00",
          "value": "Reported to Red Hat."
        },
        {
          "lang": "en",
          "time": "2023-06-20T00:00:00+00:00",
          "value": "Made public."
        }
      ],
      "datePublic": "2023-06-20T00:00:00+00:00",
      "references": [
        {
          "url": "https://access.redhat.com/security/cve/CVE-2023-3361",
          "tags": [
            "vdb-entry",
            "x_refsource_REDHAT"
          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2216588",
          "name": "RHBZ#2216588",
          "tags": [
            "issue-tracking",
            "x_refsource_REDHAT"
          ]
        },
        {
          "url": "https://github.com/opendatahub-io/odh-dashboard/issues/1415"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "A flaw was found in Red Hat OpenShift Data Science. When exporting a pipeline from the Elyra notebook pipeline editor as Python DSL or YAML, it reads S3 credentials from the cluster (ds pipeline server) and saves them in plain text in the generated output instead of an ID for a Kubernetes secret."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-200",
              "description": "Exposure of Sensitive Information to an Unauthorized Actor"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "shortName": "redhat",
        "dateUpdated": "2023-10-04T11:34:57.746Z"
      },
      "x_redhatCweChain": "CWE-200: Exposure of Sensitive Information to an Unauthorized Actor"
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2023-3361",
    "state": "PUBLISHED",
    "dateUpdated": "2024-09-19T19:18:31.545Z",
    "dateReserved": "2023-06-22T00:15:11.082Z",
    "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
    "datePublished": "2023-10-04T11:34:57.746Z",
    "assignerShortName": "redhat"
  },
  "dataVersion": "5.1"
}